version: '2'
services:      
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data
        # Enable you to access potainers web interface from your host machine
        # using http://localhost:10001
    ports:
      - "10001:9000"
 