version: '2'
services:
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      # Force publishing on the 'elk' overlay.
      network.publish_host: _eth0_
    networks:
      - elk
   
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - elk
      
      
  cassandra:
    image: docker.io/bitnami/cassandra:3-debian-10
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - cassandra_data:/bitnami
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2,CDC2_cassandra
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    networks:
      - elk
  cassandra2:
    image: docker.io/bitnami/cassandra:3-debian-10
    ports:
      - 7001:7000
      - 9043:9042
    volumes:
      - cassandra2_data:/bitnami
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
      # A web based interface for managing your docker containers.
    networks:
      - elk   
  jupyter_all_spark:
    image: jupyter/all-spark-notebook
    hostname: jupyter_all_spark
    container_name: jupyter_all_spark
    networks:
      - elk 
    volumes:
      - /jupyter-work:/work
        # Enable you to access potainers web interface from your host machine
        # using http://localhost:8888
    ports:
      - "8889:8888"      
      
volumes:
  cassandra_data:
    driver: local
  cassandra2_data:
    driver: local
    
networks:
  elk:
    driver: bridge
